BaseUrl = ""
LanguageCode = ""
Title = ""
DisqusShortname = "mybrightside"
GoogleAnalytics = ""
theme = "next"
[Params]
  Author = ""
  Birth = ""
  DateFormat = "Mon, Jan 2, 2006"
  GravatarHash = ""
  Facebook = ""
  Twitter = ""
  Github = ""
  perPage = 3
  ShowRelatedPost = true
  ShowTagCloud = false
  SyntaxHighlightTheme = "github.min.css"
  infiniteScroll = true # if true, pagination will disabled.

[Indexes]
  tag = "tags"

# MetadataFormat = "yaml"
